version: "3.0"

services:
  
  calendar-service:
    container_name: calendar-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - network-calendar-service
    depends_on:
      - postgresql
    environment:
      - JAVA_OPTS=  # You can set additional JVM options here if needed

  # PostgreSQL
  postgresql:
    container_name: postgresql
    image: postgres:15.5-alpine
    environment:
      - POSTGRES_DB=acme
      - POSTGRES_USER=postgresql-username
      - POSTGRES_PASSWORD=postgresql-password
    networks:
      - network-calendar-service
    ports:
      - 5432:5432
  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.3
    command: start-dev
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@1234
      KC_HOSTNAME_ADMIN_URL: http://88.99.248.68:8080
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: postgresql-username
      KC_DB_PASSWORD: postgresql-password
      KC_DB_URL: jdbc:postgresql://postgresql/acme
      #      PROXY_ADDRESS_FORWARDING: 'true' // deploying on vps server
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_STRICT: "false"
    depends_on:
      - postgresql
    networks:
      - network-calendar-service


#  # Elasticsearch
#  elasticsearch:
#    container_name: elasticsearch
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.12
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#    networks:
#      - network-elasticsearch
#    ports:
#      - 9200:9200
#
#  # Kibana
#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:6.8.12
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    networks:
#      - network-elasticsearch
#    depends_on:
#      - elasticsearch
#    ports:
#      - 5601:5601

networks:
  network-calendar-service:
    driver: bridge
#  network-elasticsearch:
#    driver: bridge
