#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  datasource:
    url: jdbc:postgresql://postgresql/acme
    username: postgresql-username
    password: postgresql-password
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_Notes
    locations: 'classpath:db/migration/{vendor}'
  jpa:
    properties:
      hibernate:
        check_nullability: true
        jdbc:
          time_zone: UTC
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
## Application configurations  
server:
  port: 8001
  
  # Keycloak Configurations
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/calendarService
          jwk-set-uri: http://keycloak:8080/realms/calendarService/protocol/openid-connect/certs
      client:
        registration:
          calendarService: # Keycloak Realm
            client-name: calender-ui
            client-id: calender-ui # Keycloak Client
            client-secret: htGDProqF0tcCijirPPlU4NBjLyYvzPy
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/calender-ui'
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/calendarService
            user-name-attribute: preferred_username
          calendarService:
            authorization-uri: http://keycloak:8080/realms/calendarService/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/calendarService/protocol/openid-connect/token
            jwk-set-uri: http://keycloak:8080/realms/calendarService/protocol/openid-connect/certs
            user-info-uri: http://keycloak:8080/realms/calendarService/protocol/openid-connect/userinfo
            user-name-attribute: sub
oauth2-issuer: http://keycloak:8080/realms/calendarService
# Used in authorities converter
oauth2-client-id: calender-ui
logging:
  level:
    org.springframework.security: DEBUG
springdoc.swagger-ui.operationsSorter: method
springdoc.swagger-ui.tagsSorter: alpha